# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 003e0c9c163b2b96a717bcdacc5f4adc4fcec6c243d5aae2761337c68bd316940bbe422374584051f423408e6dca50128c87cc4f20ff6799c0675c9a41fd5803

test:
  secret_key_base: e3731d851a274f5868173323f00cef588c9b9af3a188ee1dc0a60823cf75d79ce636f8d77b0bfb4a451dab210655de34630a2b185d3f477069356d52b285ae55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
